

create table T_EXPD_ADJUNTOS
(
  ID_ADJUNTO        NUMBER not null,
  ID_MAESTRA        NUMBER,
  ID_TIPO_ARCHIVO   NUMBER,
  NUMERO            INTEGER,
  FECHA             DATE,
  OBSERVACION       VARCHAR2(1000),
  ARCHIVO_BLOB		BLOB	,	
  ID_SISTEMA        INTEGER,
  NOMBRE_ARCHIVO    VARCHAR2(100),
  EXTENSION_ARCHIVO VARCHAR2(100),
  FLG_ESTADO        INTEGER default 1,
  USU_CREACION      VARCHAR2(50),
  FEC_CREACION      DATE default SYSDATE,
  IP_CREACION       VARCHAR2(50),
  USU_MODIFICACION  VARCHAR2(50),
  FEC_MODIFICACION  DATE,
  IP_MODIFICACION   VARCHAR2(50)
)
;
alter table T_EXPD_ADJUNTOS
  add constraint KEY_ADJUNTOS primary key (ID_ADJUNTO);


create table T_EXPM_DOMINIO
(
  ID_DOMINIO         NUMBER not null,
  ID_DOMINIO_PADRE   NUMBER,
  COD_DOMINIO        VARCHAR2(100),
  NOM_DOMINIO        VARCHAR2(100),
  DESC_CORTA_DOMINIO VARCHAR2(200),
  DESC_LARGA_DOMINIO VARCHAR2(1000),
  FLG_ESTADO         INTEGER default 1,
  USU_CREACION       VARCHAR2(50),
  FEC_CREACION       DATE default SYSDATE,
  IP_CREACION        VARCHAR2(50),
  USU_MODIFICACION   VARCHAR2(50),
  FEC_MODIFICACION   DATE,
  IP_MODIFICACION    VARCHAR2(50)
)
;
alter table T_EXPM_DOMINIO
  add constraint KEY_DOMINIO primary key (ID_DOMINIO);

--prompt  Creating T_EXPM_EXPEDIENTES...
create table T_EXPM_EXPEDIENTES
(
  ID_EXPEDIENTE             NUMBER not null,
  ID_PERSONAL               VARCHAR2(6),
  COD_EXPEDIENTE            VARCHAR2(9),
  FECHA_RECEPCION           DATE,
  FECHA_PRESCRIPCION        DATE,
  FECHA_HECHO               DATE,
  HOJA_RUTA                 VARCHAR2(200),
  ID_REMITENTE              NUMBER,
  ID_ACTO                   NUMBER,
  OBSERVACION_INVESTIGADORA VARCHAR2(1000),
  ID_FALTA                  NUMBER,
  ARTICULO                  VARCHAR2(200),
  INC                       VARCHAR2(200),
  OBSERVACION_INSTRUCTORA   VARCHAR2(1000),
  ID_PRECALIFICACION        NUMBER,
  TIPO_SANCION_RECOMENDADA  VARCHAR2(200),
  ACTO_INICIO               VARCHAR2(100),
  FECHA_NOTIFICACION        DATE,
  RECOMENDACION_PREINFORME  VARCHAR2(200),
  ID_SANCION_RECOMENDADA    NUMBER,
  ID_ORGANO_INSTRUCTOR      NUMBER,
  FECHA_NOTIFICACION_INICIO DATE,
  DOCUMENTO_FINALIZACION    VARCHAR2(200),
  RECOMENDACION_INSTRUCTOR  VARCHAR2(200),
  ID_ORGANO_SANCIONADOR     NUMBER,
  SANCION                   VARCHAR2(200),
  OBSERVACION_SANCIONADORA  VARCHAR2(1000),
  ID_SITUACION              NUMBER,
  ID_ESTADO                 NUMBER,
  FLG_ESTADO                INTEGER default 1,
  USU_CREACION              VARCHAR2(50),
  FEC_CREACION              DATE default SYSDATE,
  IP_CREACION               VARCHAR2(50),
  USU_MODIFICACION          VARCHAR2(50),
  FEC_MODIFICACION          DATE,
  IP_MODIFICACION           VARCHAR2(50)
)
;
alter table T_EXPM_EXPEDIENTES
  add constraint KEY primary key (ID_EXPEDIENTE);

--prompt  Creating T_EXPM_FORMATO_CORREO...
create table T_EXPM_FORMATO_CORREO
(
  ID_FORMATO       NUMBER not null,
  ASUNTO           VARCHAR2(500) not null,
  BODY             VARCHAR2(4000),
  FLG_ESTADO       INTEGER default 1,
  USU_CREACION     VARCHAR2(50),
  FEC_CREACION     DATE default SYSDATE,
  IP_CREACION      VARCHAR2(50),
  USU_MODIFICACION VARCHAR2(50),
  FEC_MODIFICACION DATE,
  IP_MODIFICACION  VARCHAR2(50)
)
;
alter table T_EXPM_FORMATO_CORREO
  add primary key (ID_FORMATO);

--prompt  Disabling triggers for T_EXPD_ADJUNTOS...
alter table T_EXPD_ADJUNTOS disable all triggers;
--prompt  Disabling triggers for T_EXPM_DOMINIO...
alter table T_EXPM_DOMINIO disable all triggers;
--prompt  Disabling triggers for T_EXPM_EXPEDIENTES...
alter table T_EXPM_EXPEDIENTES disable all triggers;
--prompt  Disabling triggers for T_EXPM_FORMATO_CORREO...
alter table T_EXPM_FORMATO_CORREO disable all triggers;
--prompt  Loading T_EXPD_ADJUNTOS...
--prompt  Table is empty
--prompt  Loading T_EXPM_DOMINIO...
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (1, 0, 'TIPO_ADJ', 'T_TIPO_ADJUNTO', 'Tipo de archivos', 'Tipo de archivos', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (2, 0, 'TIPACT', 'T_TIPO_ACTO', 'Tipo actos', 'Tipo actos', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (3, 0, 'TIPFAL', 'T_TIPO_FALTA', 'Tipo falta', 'Tipo falta', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (4, 0, 'TIPSAN', 'T_TIPO_SANCION', 'Tipo sanción', 'Tipo sanción', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (5, 0, 'ESTADO', 'T_ESTADO', 'Estados', 'Estados', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (6, 0, 'SITUACION', 'T_SITUACION', 'Situación', 'Situación', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (7, 1, 'NOTAIN', 'TIPO_ADJ', 'Notificación Acto de Inicio', '' || chr(9) || 'Not. Acto Inicio', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (8, 1, 'INIPAD', 'TIPO_ADJ', 'Inicio Proceso Administrativo Disciplinario', '' || chr(9) || 'Inicio PAD', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (9, 1, 'INFPRE', 'TIPO_ADJ', '' || chr(9) || 'Informe de Precalificacion', '' || chr(9) || 'Inf. Precalificacion', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (10, 1, 'INFINS', 'TIPO_ADJ', '' || chr(9) || 'Informe de Instrucción', '' || chr(9) || 'Inf. INstruccion', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (11, 1, 'DOCDES', 'TIPO_ADJ', '' || chr(9) || 'Documento de Descargo', '' || chr(9) || 'Doc. Descargo', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (12, 1, 'DOCCON', 'TIPO_ADJ', 'Documento Conclusión PAD', '' || chr(9) || 'Doc. Conclusión PAD', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (13, 2, 'DENUNC', 'TIPACT', '' || chr(9) || 'Denuncia', '' || chr(9) || 'Denuncia', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (14, 2, 'CORRUP', 'TIPACT', '' || chr(9) || 'Corrupción', '' || chr(9) || 'Corrupción', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('01-11-2021 10:55:18', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (15, 2, 'CONTRO', 'TIPACT', '' || chr(9) || 'Contraloría', '' || chr(9) || 'Contraloría', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (16, 2, 'ADMINI', 'TIPACT', '' || chr(9) || 'Adminstrativo', '' || chr(9) || 'Adminstrativo', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('30-10-2021 16:55:12', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (17, 3, 'RIS', 'TIPFAL', '' || chr(9) || 'RIS', '' || chr(9) || 'RIS', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (18, 3, '30057', 'TIPFAL', '' || chr(9) || '30057', '' || chr(9) || '30057', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (19, 3, '27815', 'TIPFAL', '' || chr(9) || '27815', '' || chr(9) || '27815' || chr(9) || '', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('30-10-2021 17:17:35', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (21, 4, 'DESTIT', 'TIPSAN', '' || chr(9) || 'Destitución', '' || chr(9) || 'Destitución', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (22, 4, 'AMONES', 'TIPSAN', '' || chr(9) || 'Amonestación', '' || chr(9) || 'Amonestación', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (23, 4, 'ABSOLU', 'TIPSAN', '' || chr(9) || 'Absolución', '' || chr(9) || 'Absolución', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (24, 5, 'PE', 'ESTADO', '' || chr(9) || 'Pendiente', '' || chr(9) || 'Pendiente', 1, 'admin', to_date('30-10-2021 10:12:19', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (25, 5, 'AT', 'ESTADO', 'Atendido', 'Atendido', 1, 'admin', to_date('30-10-2021 10:12:19', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (26, 6, 'ETASAN', 'SITUACION', '' || chr(9) || 'Etapa Sancionadora', '' || chr(9) || 'Etapa Sancionadora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (27, 6, 'ETAINV', 'SITUACION', '' || chr(9) || 'Etapa Investigatora', '' || chr(9) || 'Etapa Investigatora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (28, 6, 'ETAINS', 'SITUACION', '' || chr(9) || 'Etapa Instructora', '' || chr(9) || 'Etapa Instructora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
commit;
--prompt  27 records loaded
--prompt  Loading T_EXPM_EXPEDIENTES...
insert into T_EXPM_EXPEDIENTES (ID_EXPEDIENTE, ID_PERSONAL, COD_EXPEDIENTE, FECHA_RECEPCION, FECHA_PRESCRIPCION, FECHA_HECHO, HOJA_RUTA, ID_REMITENTE, ID_ACTO, OBSERVACION_INVESTIGADORA, ID_FALTA, ARTICULO, INC, OBSERVACION_INSTRUCTORA, ID_PRECALIFICACION, TIPO_SANCION_RECOMENDADA, ACTO_INICIO, FECHA_NOTIFICACION, RECOMENDACION_PREINFORME, ID_SANCION_RECOMENDADA, ID_ORGANO_INSTRUCTOR, FECHA_NOTIFICACION_INICIO, DOCUMENTO_FINALIZACION, RECOMENDACION_INSTRUCTOR, ID_ORGANO_SANCIONADOR, SANCION, OBSERVACION_SANCIONADORA, ID_SITUACION, ID_ESTADO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (8, '001930', 'EXP000008', to_date('02-11-2021', 'dd-mm-yyyy'), to_date('06-11-2021', 'dd-mm-yyyy'), to_date('02-11-2021', 'dd-mm-yyyy'), 'hoja ruta xd', 6, 14, 'OBSERVACION INVSTI XD', 17, 'ARTICULL1 XD ', 'INC1 XD ', 'ONSRVACON INSTRITUTORA', 18, 'SANCION RECO1 XD ', 'ACTO INI1XD ', to_date('11-11-2021', 'dd-mm-yyyy'), 'PREINFORME XD', 22, 98, to_date('20-11-2021', 'dd-mm-yyyy'), 'DOCUM FIN', 'INSTRUCTOR', 36, 'SANCION 1', 'OBSEVRCAON FINAL', 27, 24, 1, 'IPEREZ', to_date('02-11-2021 15:33:38', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', 'IPEREZ', to_date('03-11-2021 18:24:42', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into T_EXPM_EXPEDIENTES (ID_EXPEDIENTE, ID_PERSONAL, COD_EXPEDIENTE, FECHA_RECEPCION, FECHA_PRESCRIPCION, FECHA_HECHO, HOJA_RUTA, ID_REMITENTE, ID_ACTO, OBSERVACION_INVESTIGADORA, ID_FALTA, ARTICULO, INC, OBSERVACION_INSTRUCTORA, ID_PRECALIFICACION, TIPO_SANCION_RECOMENDADA, ACTO_INICIO, FECHA_NOTIFICACION, RECOMENDACION_PREINFORME, ID_SANCION_RECOMENDADA, ID_ORGANO_INSTRUCTOR, FECHA_NOTIFICACION_INICIO, DOCUMENTO_FINALIZACION, RECOMENDACION_INSTRUCTOR, ID_ORGANO_SANCIONADOR, SANCION, OBSERVACION_SANCIONADORA, ID_SITUACION, ID_ESTADO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (10, '001930', 'EXP000010', to_date('06-11-2021', 'dd-mm-yyyy'), to_date('13-11-2021', 'dd-mm-yyyy'), to_date('06-11-2021', 'dd-mm-yyyy'), 'hoja 1', 6, 0, null, 0, null, null, null, 0, null, null, null, null, 0, 0, null, null, null, 0, null, null, 0, 0, 1, 'IPEREZ', to_date('06-11-2021 12:47:41', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', null, null, null);
insert into T_EXPM_EXPEDIENTES (ID_EXPEDIENTE, ID_PERSONAL, COD_EXPEDIENTE, FECHA_RECEPCION, FECHA_PRESCRIPCION, FECHA_HECHO, HOJA_RUTA, ID_REMITENTE, ID_ACTO, OBSERVACION_INVESTIGADORA, ID_FALTA, ARTICULO, INC, OBSERVACION_INSTRUCTORA, ID_PRECALIFICACION, TIPO_SANCION_RECOMENDADA, ACTO_INICIO, FECHA_NOTIFICACION, RECOMENDACION_PREINFORME, ID_SANCION_RECOMENDADA, ID_ORGANO_INSTRUCTOR, FECHA_NOTIFICACION_INICIO, DOCUMENTO_FINALIZACION, RECOMENDACION_INSTRUCTOR, ID_ORGANO_SANCIONADOR, SANCION, OBSERVACION_SANCIONADORA, ID_SITUACION, ID_ESTADO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (9, '001930', 'EXP000009', to_date('11-11-2021', 'dd-mm-yyyy'), to_date('13-11-2021', 'dd-mm-yyyy'), to_date('13-11-2021', 'dd-mm-yyyy'), 'HOJA RUTA', 6, 14, 'obs1', 19, 'ARTICULO', 'ddfgdfgdf', 'OBS', 17, 'fgdfgd', 'ACTO INI1XD ', to_date('11-11-2021', 'dd-mm-yyyy'), 'fgfd', 21, 3, to_date('04-11-2021', 'dd-mm-yyyy'), 'ghfghfg', 'fghghfg', 6, 'fdgdfdxd', 'OBS', 27, 24, 1, 'IPEREZ', to_date('04-11-2021 11:13:57', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', 'IPEREZ', to_date('04-11-2021 11:17:54', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
commit;
--prompt  3 records loaded
--prompt  Loading T_EXPM_FORMATO_CORREO...
insert into T_EXPM_FORMATO_CORREO (ID_FORMATO, ASUNTO, BODY, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (3, 'asunto', '<p>hola <span style="background-color: rgb(255, 255, 0);">hghhhhh&nbsp;<b>&nbsp;dfgdfgdgdf fg<u>&nbsp;dfgdfgfdg</u></b></span></p>', 1, 'IPEREZ', to_date('04-11-2021 11:22:46', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', null, null, null);
insert into T_EXPM_FORMATO_CORREO (ID_FORMATO, ASUNTO, BODY, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (1, 'ASUNTO X', '<p>HOLA QUE TAL XD XD<span style="background-color: rgb(255, 255, 0);">XD</span></p>', 1, 'IPEREZ', to_date('01-11-2021 09:10:15', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', null, null, null);
insert into T_EXPM_FORMATO_CORREO (ID_FORMATO, ASUNTO, BODY, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (2, 'ASUNTO 2 33', '<p>HOLA <span style="background-color: rgb(255, 255, 0);">SOMBREADO</span></p><ol><li><span style="background-color: rgb(255, 255, 0);">PUNTO 1&nbsp;</span></li><li><span style="background-color: rgb(255, 255, 0);">PUNTO 2</span></li><li><span style="background-color: rgb(255, 255, 0);">3.xd</span></li></ol>', 1, 'IPEREZ', to_date('01-11-2021 09:11:43', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', 'IPEREZ', to_date('01-11-2021 10:02:08', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
commit;
--prompt  3 records loaded
--prompt  Enabling triggers for T_EXPD_ADJUNTOS...
alter table T_EXPD_ADJUNTOS enable all triggers;
--prompt  Enabling triggers for T_EXPM_DOMINIO...
alter table T_EXPM_DOMINIO enable all triggers;
--prompt  Enabling triggers for T_EXPM_EXPEDIENTES...
alter table T_EXPM_EXPEDIENTES enable all triggers;
--prompt  Enabling triggers for T_EXPM_FORMATO_CORREO...
alter table T_EXPM_FORMATO_CORREO enable all triggers;

