

--prompt  Disabling triggers for APP_GESEXPDIS.T_EXPM_DOMINIO...
alter table APP_GESEXPDIS.T_EXPM_DOMINIO disable all triggers;
--prompt  Loading APP_GESEXPDIS.T_EXPM_DOMINIO...
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (1, 0, 'TIPO_ADJ', 'T_TIPO_ADJUNTO', 'Tipo de archivos', 'Tipo de archivos', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (2, 0, 'TIPACT', 'T_TIPO_ACTO', 'Tipo actos', 'Tipo actos', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (3, 0, 'TIPFAL', 'T_TIPO_FALTA', 'Tipo falta', 'Tipo falta', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (4, 0, 'TIPSAN', 'T_TIPO_SANCION', 'Tipo sanción', 'Tipo sanción', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (5, 0, 'ESTADO', 'T_ESTADO', 'Estados', 'Estados', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (6, 0, 'SITUACION', 'T_SITUACION', 'Situación', 'Situación', 1, 'admin', to_date('22-10-2021', 'dd-mm-yyyy'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (7, 1, 'NOTAIN', 'TIPO_ADJ', 'Notificación Acto de Inicio', '' || chr(9) || 'Not. Acto Inicio', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (8, 1, 'INIPAD', 'TIPO_ADJ', 'Inicio Proceso Administrativo Disciplinario', '' || chr(9) || 'Inicio PAD', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (9, 1, 'INFPRE', 'TIPO_ADJ', '' || chr(9) || 'Informe de Precalificacion', '' || chr(9) || 'Inf. Precalificacion', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (10, 1, 'INFINS', 'TIPO_ADJ', '' || chr(9) || 'Informe de Instrucción', '' || chr(9) || 'Inf. INstruccion', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (11, 1, 'DOCDES', 'TIPO_ADJ', '' || chr(9) || 'Documento de Descargo', '' || chr(9) || 'Doc. Descargo', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (12, 1, 'DOCCON', 'TIPO_ADJ', 'Documento Conclusión PAD', '' || chr(9) || 'Doc. Conclusión PAD', 1, 'admin', to_date('30-10-2021 10:06:48', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (13, 2, 'DENUNC', 'TIPACT', '' || chr(9) || 'Denuncia', '' || chr(9) || 'Denuncia', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (14, 2, 'CORRUP', 'TIPACT', '' || chr(9) || 'Corrupción', '' || chr(9) || 'Corrupción', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('01-11-2021 10:55:18', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (15, 2, 'CONTRO', 'TIPACT', '' || chr(9) || 'Contraloría', '' || chr(9) || 'Contraloría', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (16, 2, 'ADMINI', 'TIPACT', '' || chr(9) || 'Adminstrativo', '' || chr(9) || 'Adminstrativo', 1, 'admin', to_date('30-10-2021 10:08:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('30-10-2021 16:55:12', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (50, 5, 'C', 'ESTADO', 'Concluido', 'Concluido', 1, 'WDELGADO', to_date('14-11-2021 16:14:54', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (44, 1, 'EXP', 'TIPO_ADJ', 'EXPEDIENTE 1', 'EXPEDIENTE 1', 1, 'WDELGADO', to_date('12-11-2021 16:21:01', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11', null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (17, 3, 'RIS', 'TIPFAL', '' || chr(9) || 'RIS', '' || chr(9) || 'RIS', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (18, 3, '30057', 'TIPFAL', '' || chr(9) || '30057', '' || chr(9) || '30057', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (19, 3, '27815', 'TIPFAL', '' || chr(9) || '27815', '' || chr(9) || '27815' || chr(9) || '', 1, 'admin', to_date('30-10-2021 10:09:32', 'dd-mm-yyyy hh24:mi:ss'), null, 'IPEREZ', to_date('30-10-2021 17:17:35', 'dd-mm-yyyy hh24:mi:ss'), '192.168.1.11');
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (21, 4, 'DESTIT', 'TIPSAN', '' || chr(9) || 'Destitución', '' || chr(9) || 'Destitución', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (22, 4, 'AMONES', 'TIPSAN', '' || chr(9) || 'Amonestación', '' || chr(9) || 'Amonestación', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (23, 4, 'ABSOLU', 'TIPSAN', '' || chr(9) || 'Absolución', '' || chr(9) || 'Absolución', 1, 'admin', to_date('30-10-2021 10:10:52', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (24, 5, 'PE', 'ESTADO', '' || chr(9) || 'Pendiente', '' || chr(9) || 'Pendiente', 1, 'admin', to_date('30-10-2021 10:12:19', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (25, 5, 'AT', 'ESTADO', 'Atendido', 'Atendido', 1, 'admin', to_date('30-10-2021 10:12:19', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (26, 6, 'ETASAN', 'SITUACION', '' || chr(9) || 'Etapa Sancionadora', '' || chr(9) || 'Etapa Sancionadora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (27, 6, 'ETAINV', 'SITUACION', '' || chr(9) || 'Etapa Investigatora', '' || chr(9) || 'Etapa Investigatora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
insert into APP_GESEXPDIS.T_EXPM_DOMINIO (ID_DOMINIO, ID_DOMINIO_PADRE, COD_DOMINIO, NOM_DOMINIO, DESC_CORTA_DOMINIO, DESC_LARGA_DOMINIO, FLG_ESTADO, USU_CREACION, FEC_CREACION, IP_CREACION, USU_MODIFICACION, FEC_MODIFICACION, IP_MODIFICACION)
values (28, 6, 'ETAINS', 'SITUACION', '' || chr(9) || 'Etapa Instructora', '' || chr(9) || 'Etapa Instructora', 1, 'admin', to_date('30-10-2021 10:13:30', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null);
commit;
--prompt  29 records loaded
--prompt  Enabling triggers for APP_GESEXPDIS.T_EXPM_DOMINIO...
alter table APP_GESEXPDIS.T_EXPM_DOMINIO enable all triggers;

--prompt  Done.
