grant select on BITACORA.t_bitl_oficina to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITM_PERSONAL to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITJ_PERSONAL_OFICINA to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITL_OFICINA to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITL_SITUACION_LABORAL to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITD_PERSONAL_INCORPORACION to APP_GESEXPDIS;
grant select  ON BITACORA.T_BITD_PERSONAL_DNI to APP_GESEXPDIS;
grant select  ON BITACORA.V_PUESTO to APP_GESEXPDIS;