grant select on BITACORA.t_bitl_oficina to EXPEDIENTES;
grant select  ON BITACORA.T_BITM_PERSONAL to EXPEDIENTES;
grant select  ON BITACORA.T_BITJ_PERSONAL_OFICINA to EXPEDIENTES;
grant select  ON BITACORA.T_BITL_OFICINA to EXPEDIENTES;
grant select  ON BITACORA.T_BITL_SITUACION_LABORAL to EXPEDIENTES;
grant select  ON BITACORA.T_BITD_PERSONAL_INCORPORACION to EXPEDIENTES;
grant select  ON BITACORA.T_BITD_PERSONAL_DNI to EXPEDIENTES;